awsdocs/aws-sdk-for-javascript-v3

doc_source/getting-started-react-native.md
fixing broken link of react native example
Misspelling of `App.js ` link  issue #34
fixing broken link of `react native example` 
=> fixing broken link

doc_source/migrating-to-v3.md
N/A
Add link to Upgrading Notes from GitHub repo
=> Add link to Upgrading Notes from GitHub repo

doc_source/migrating-to-v3.md
N/A
add missing equals signs in migration guide
=> fix: add missing equals signs in migration guide

doc_source/migrating-to-v3.md
Follow-up to https://github.com/awsdocs/aws-sdk-for-javascript-v3/pull/12
prettify and fix bugs with migration guide
* Use `const` everywhere.
* Use `client` instead of `s3` to avoid confusion with import.
* Fix async arrow function.
* call run function in callback example.
=> chore: prettify and fix bugs with migration guide

doc_source/getting-started-nodejs.md
Spotted a Reddit post poking fun at the lack of steps 2 & 3 (https://i.redd.it/4xchyhksmgi61.jpg)
=> Fixed step numbering

doc_source/getting-started-nodejs.md
Fixed a few minor typos that would cause errors for someone who copy-and-pasted the code without double checking it.
=> Minor typo corrections for those copy-and-pasting

doc_source/getting-started-react-native.md
Fix code example indentation on [Getting started in React Native](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/getting-started-react-native.html) page 
=> docs: fix react native code example indentation

doc_source/migrating-to-v3.md
Fix few minor javascript issues in the examples for migrating from v2 to v3
=> docs: Fix migration examples

doc_source/dynamodb-example-dynamodb-utilities.md
=> Example code syntax highlight

doc_source/s3-example-creating-buckets.md
the documentation has 2 identicle article for the create s3 bucket
removal of the duplicate article
=> duplicate "create s3 bucket" section

doc_source/node-configuring-proxies.md
I landed to this page through google search, and didn't know about NodeHttpHandler and took extra effort to investigate what it is and how to import it.
Adding a require statement in the example as the previous pages do.
=> update example in node-configuring-proxies.md

doc_source/enforcing-tls.md
Internal JS-2966
Update Enforcing TLS to use 1.3
=> Update Enforcing TLS to use 1.3

doc_source/welcome.md
=> Remove the redundant link

doc_source/s3-example-creating-buckets.md
Issue #, if available:
Description of changes:
fix: Update the s3Client to the correct name variable for JS code snip. Also please reference this [PR 57 amazon-s3-userguide](https://github.com/awsdocs/amazon-s3-userguide/pull/57)
=> fix: Update the s3Client to the correct name variable for JS code snip

doc_source/sqs-examples-send-receive-messages.md
=> docs(sqs): change var to const

doc_source/sns-examples-publishing-messages.md
=> docs(sns): change var to const

doc_source/sns-examples-sending-sms.md
* Changed var to const as this is the convention throughout the docs
* It makes a lot more sense to start with sending an SMS since this is what most users will most likely want to know
=> docs(sns): update order of example and convert var to const

doc_source/getting-started-nodejs.md
rename `sampleClient.js` to be `sample.js`
=> update file name in sample

doc_source/getting-started-nodejs.md
=> Fix small typo in getting-started-nodejs.md

doc_source/node-registering-certs.md
*Issue #, if available:* Resolves #69
*Description of changes:* Update node certificate bundle example.
=> Update certificate bundle example. (#69)

doc_source/node-configuring-proxies.md
*Issue #, if available:* #67
*Description of changes:* Updated the proxy agent example to use a maintained and functioning library. This will save developers countless hours of debugging until they realize the current example is no longer a viable solution.
Resolves #67
=> Change proxy agent example. (#67)
